name: Docker Image CI

# Trigger workflow on push and pr events
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # git checkout code
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Set up QEMU, later docker buildx depends on this.
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0

      # Set up Docker buildx to facilitate building Multi platform images
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Login to DockerHub
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker and push to Docker hub
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          build-args: |
            HatH_VERSION=${{ vars.HatH_VERSION }}
            HatH_SHA256=${{ vars.HatH_SHA256 }}
          context: .
          # Generate multi-platform images,see https://github.com/docker-library/bashbrew/blob/v0.1.11/architecture/oci-platform.go
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            kinnrai/hath:${{ github.ref_name }}