name: Docker Image CI

# Trigger workflow when push tag
on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  HatH_VERSION: ''

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # git checkout code
      - name: Check
        uses: actions/checkout@v4.1.1

      # Set up QEMU, later docker buildx depends on this.
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0

      # Set up Docker buildx to facilitate building Multi platform images
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Login to DockerHub
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Obtain the current tag information through the git command and store it in the environment variable HatH_VERSION
      - name: Generate HatH_VERSION
        run: echo HatH_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      # Build Docker and push to Docker hub
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          build-args: HatH_VERSION=${{ env.HatH_VERSION }}
          context: .
          # Generate multi-platform images,see https://github.com/docker-library/bashbrew/blob/v0.1.11/architecture/oci-platform.go
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
          push: true
          tags: |
            kinnrai/hath:latest
            kinnrai/hath:${{ secrets.HatH_VERSION }}
